# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2146083b51af0c13d08464cc65c84c5db963bdf450a44b940c8c3a2b5c8d919a71adcda6ad2a311adac0e0ba00eaf53a85dafa8728c0195679c0f2ea5c09332a

test:
  secret_key_base: eee654cc6cce70a9a4a7b9ccf875be5bc95054a520a27a0cd5a8f906943793fca4382e31f2b79a4fc55007104d3fbb26fd7db7434e60a45f7afb3f52f7eaa453

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
